name: Unpack Zip
on: [push]
jobs:
  unpack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Unzip Rescue
        run: |
          if [ -f rescue.zip ]; then
            unzip -o rescue.zip
            rm rescue.zip
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add .
            git commit -m "The robot unpacked your code"
            git push
          fi
